#pragma once

#define QSTATE_VERSION_MAJOR 0
#define QSTATE_VERSION_MINOR 1
#define QSTATE_VERSION_PATCH 6
#define QSTATE_VERSION_STRING "0.1.6"

#define QSTATE_ABI_VERSION_MAJOR 1
#define QSTATE_ABI_VERSION_MINOR 5
#define QSTATE_ABI_VERSION_PATCH 0
